### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by rock211212** [elBukkit/MagicWorlds#5]
i install MagicWorlds in my 1.11.2 sever 
nothing change in the world
and i can't found wand in the world

**Comment by NathanWolf** [comment]
You have to install some configs for it to do anything.

I don't really have it hide wands anymore since that doesn't make any sense, no one needs a bunch of wands. I have some configs to add SP to chests and to spawn magic mobs, configs for the Other Side- just take a look through here and take whatever you want, or make up your own.

https://github.com/elBukkit/MagicWorlds/tree/master/src/main/resources/examples
